fix: commits not pushed

diff --git a/scripts/process-git-dirs b/scripts/process-git-dirs
--- a/scripts/process-git-dirs
+++ b/scripts/process-git-dirs
@@ -23,24 +23,24 @@ case "$mode" in
               # Check if local commits have been pushed to remote
               local commits=$(git rev-list --count HEAD~..HEAD)
               if [ "$commits" -gt 0 ]; then
-                echo "🟡 Local commits haven't been pushed in '$d'"
+                echo "\t 🟡 Local commits haven't been pushed in '$d'"
               fi
 
               # Check if local changes exist. And count number of files
               local local_file_changes=$(git diff HEAD --name-only | wc -l | xarg)
               if [ -n "$local_file_changes" ]; then
-                echo "🟡 Local file changes in '$d' files."
+                echo "\t 🟡 Local file changes in '$d' files."
               fi
             fi
           else
-            echo "Directory '$d' is not a git repository"
+            echo "\t Directory '$d' is not a git repository"
           fi
           cd "$prev_dir" >/dev/null 2>&1 || true
         else
-          echo "Failed to cd into '$d'"
+          echo "\t Failed to cd into '$d'"
         fi
       else
-        echo "Directory '$d' does not exist!"
+        echo "\t Directory '$d' does not exist!"
       fi
     done
     ;;
@@ -48,27 +48,63 @@ case "$mode" in
     echo "Displaying git status for provided directories..."
     for d in "${dirs[@]}"; do
       if [ -d "$d" ]; then
-        echo "‣ $d"
+        echo "\n\t ‣ $d"
         prev_dir=$(pwd)
+
+        # Check dir
         if cd "$d"; then
+
+          # Check if it is a git directory
           if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-            if [ -n "$(git status --porcelain)" ]; then
-              count=$(git status --porcelain | wc -l)
-              echo -e "\t 🟡 local changes need to be committed: $count file(s)"
-            else
-              echo -e "\t ✅ clean working tree"
+            if [ $? -eq 0 ]; then
+
+              # Check if local commits have been pushed to remote
+              local commits=$(git rev-list --count @{u}..HEAD)
+              if [ "$commits" -gt 0 ]; then
+                echo "\t 🟡 Local commits haven't been pushed in '$d'"
+              fi
+
+              # Check if local changes exist. And count number of files
+              local local_file_changes=$(git diff HEAD --name-only | wc -l | xargs)
+              if [ -n "$local_file_changes" ]; then
+                echo "\t 🟡 Local file changes in '$d' files."
+              fi
             fi
           else
-            echo "\t Not a git repository"
+            echo "\t Directory '$d' is not a git repository"
           fi
           cd "$prev_dir" >/dev/null 2>&1 || true
         else
-          echo "Failed to cd into '$d'"
+          echo "\t Failed to cd into '$d'"
         fi
       else
-        echo "Directory '$d' does not exist!"
+        echo "\t Directory '$d' does not exist!"
       fi
     done
+
+    # for d in "${dirs[@]}"; do
+    #   if [ -d "$d" ]; then
+    #     echo "‣ $d"
+    #     prev_dir=$(pwd)
+    #     if cd "$d"; then
+    #       if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+    #         if [ -n "$(git status --porcelain)" ]; then
+    #           count=$(git status --porcelain | wc -l)
+    #           echo -e "\t 🟡 local changes need to be committed: $count file(s)"
+    #         else
+    #           echo -e "\t ✅ clean working tree"
+    #         fi
+    #       else
+    #         echo "\t Not a git repository"
+    #       fi
+    #       cd "$prev_dir" >/dev/null 2>&1 || true
+    #     else
+    #       echo "Failed to cd into '$d'"
+    #     fi
+    #   else
+    #     echo "Directory '$d' does not exist!"
+    #   fi
+    # done
     ;;
   pull)
     echo "Pulling latest changes for provided directories..."
